services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  competencies-ecoe-service:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DB_URL}
    command: npm run start:prod

volumes:
  pgdata:
  rabbitmq_data: